[project]
name = "systeller"
version = "0.1.0"
description = "Python library for system communication"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "plyer>=2.1.0",
    "pyttsx3>=2.98",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true
